[versions]
kotlin = "2.0.20"
joml = "1.10.8"
kotlinx-json = "1.7.3"

[libraries]
joml = { module = "org.joml:joml", version.ref = "joml" }
kotlinx-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-json" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
