name: Build bam2json and release library on Maven Central

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '20'
          cache: 'gradle'

      - run: ./gradlew --no-daemon --console plain :app:shadowJar && mv app/build/libs/app-*-all.jar ./bam2json.jar

      - name: Create bam2json release
        uses: softprops/action-gh-release@v2
        with:
          files: ./bam2json.jar

      - name: Setup GPG keys for signing
        run: |
          echo -e "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          gpg --list-keys

      - name: Setup Maven Central credentials
        run: |
          mkdir ~/.jreleaser
          echo "JRELEASER_DEPLOY_MAVEN_MAVENCENTRAL_SONATYPE_USERNAME=${{ secrets.MAVENCENTRAL_USERNAME }}" > ~/.jreleaser/config.properties
          echo "JRELEASER_DEPLOY_MAVEN_MAVENCENTRAL_SONATYPE_PASSWORD=${{ secrets.MAVENCENTRAL_PASSWORD }}" >> ~/.jreleaser/config.properties
          echo "JRELEASER_GPG_PASSPHRASE=*" >> ~/.jreleaser/config.properties

      - name: Run :releaseLibrary
        run: ./gradlew --no-daemon --console plain :releaseLibrary
