name: Build bam2json

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 20
        uses: actions/setup-java@v1
        with:
          java-version: 20
      - run: ./gradlew --console plain :app:shadowJar
      - run: mv app/build/libs/app-1.0-SNAPSHOT-all.jar ./bam2json.jar
      - uses: actions/upload-artifact@v4
        name: bam2json
        path: ./bam2json.jar