name: Build bam2json

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '20'
          cache: 'gradle'
      - run: ./gradlew --no-daemon --console plain :app:shadowJar
      - run: mv app/build/libs/app-1.0-SNAPSHOT-all.jar ./bam2json.jar
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: ./bam2json.jar